from __future__ import annotations

import base64
import json
import mimetypes
import re
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components
from bs4 import BeautifulSoup


# ============================================================
# PATHS / PAGE
# ============================================================

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"

st.set_page_config(
    page_title="Arbor QSF Explorer",
    page_icon="🌲",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# DATA HELPERS
# ============================================================

@st.cache_data(show_spinner=False)
def read_csv_optional(filename: str) -> pd.DataFrame:
    path = DATA / filename
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


@st.cache_data(show_spinner=False)
def read_meta() -> dict:
    path = DATA / "report_meta.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def finite_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce").replace(
        [np.inf, -np.inf], np.nan
    )


def get_qsm_inventory(df: pd.DataFrame) -> pd.DataFrame:
    required = ["DBH_cm", "H_m", "Volume_total_m3"]
    if not all(c in df.columns for c in required):
        return pd.DataFrame()

    out = df.copy()
    for c in required:
        out[c] = finite_numeric(out[c])

    return out[
        out["DBH_cm"].notna()
        & out["H_m"].notna()
        & out["Volume_total_m3"].notna()
    ].copy()


def fmt(value, digits=1, suffix=""):
    try:
        if pd.isna(value):
            return "NA"
        return f"{float(value):,.{digits}f}{suffix}"
    except Exception:
        return "NA"


# ============================================================
# INLINE LOCAL HTMLWIDGET ASSETS
#
# QSM viewer pages were generated by R htmlwidgets with
# selfcontained = FALSE. On Streamlit Community Cloud we read
# the selected HTML file and inline its local JS/CSS assets
# before passing it to components.html().
# ============================================================

def _is_remote(url: str) -> bool:
    u = url.lower().strip()
    return (
        u.startswith("http://")
        or u.startswith("https://")
        or u.startswith("//")
        or u.startswith("data:")
        or u.startswith("blob:")
        or u.startswith("#")
    )


def _inline_css_urls(css_text: str, css_dir: Path) -> str:
    pattern = re.compile(r"url\((['\"]?)([^)'\"\s]+)\1\)")

    def repl(match):
        raw = match.group(2).strip()
        if _is_remote(raw):
            return match.group(0)

        asset = (css_dir / raw).resolve()
        if not asset.exists() or not asset.is_file():
            return match.group(0)

        mime = mimetypes.guess_type(asset.name)[0] or "application/octet-stream"
        encoded = base64.b64encode(asset.read_bytes()).decode("ascii")
        return f"url(data:{mime};base64,{encoded})"

    return pattern.sub(repl, css_text)


@st.cache_data(show_spinner=False)
def inline_html_file(path_string: str, mtime_ns: int) -> str:
    """
    Read a generated QSM HTML viewer and inline all local JS/CSS.
    mtime_ns is included only to invalidate the Streamlit cache if
    the viewer file changes.
    """
    path = Path(path_string)
    html = path.read_text(encoding="utf-8", errors="replace")
    soup = BeautifulSoup(html, "html.parser")

    # Inline local stylesheets.
    for link in list(soup.find_all("link", href=True)):
        rel = [str(x).lower() for x in (link.get("rel") or [])]
        if "stylesheet" not in rel:
            continue

        href = link.get("href", "")
        if not href or _is_remote(href):
            continue

        css_path = (path.parent / href).resolve()
        if not css_path.exists():
            continue

        css = css_path.read_text(encoding="utf-8", errors="replace")
        css = _inline_css_urls(css, css_path.parent)

        style = soup.new_tag("style")
        style.string = css
        link.replace_with(style)

    # Inline local JavaScript.
    for script in list(soup.find_all("script", src=True)):
        src = script.get("src", "")
        if not src or _is_remote(src):
            continue

        js_path = (path.parent / src).resolve()
        if not js_path.exists():
            continue

        js = js_path.read_text(encoding="utf-8", errors="replace")
        new_script = soup.new_tag("script")
        new_script.string = js
        script.replace_with(new_script)

    # Remove base tags if present, because the widget is injected into
    # a Streamlit component iframe rather than opened from disk.
    for base_tag in soup.find_all("base"):
        base_tag.decompose()

    return str(soup)


def resolve_viewer_path(viewer_value: str) -> Optional[Path]:
    if not isinstance(viewer_value, str) or not viewer_value.strip():
        return None

    value = viewer_value.replace("\\", "/").strip()

    # Manifest usually contains QSM_viewers/tree_XXXXX.html.
    candidates = [
        DATA / value,
        DATA / "QSM_viewers" / Path(value).name,
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()

    return None


# ============================================================
# LOAD DATA
# ============================================================

meta = read_meta()

inventory = read_csv_optional("03_tree_inventory_QSM.csv")
ranking = read_csv_optional("Arbor_best_trees_structural.csv")
manifest = read_csv_optional("QSM_viewer_manifest.csv")
treemap = read_csv_optional("QSF_treemap.csv")
semantic_before = read_csv_optional("QSF_semantic_before_sample.csv")
semantic_after = read_csv_optional("QSF_semantic_after_sample.csv")
semantic_transition = read_csv_optional("QSF_semantic_transition_sample.csv")

if inventory.empty:
    st.error(
        "03_tree_inventory_QSM.csv was not found in the data folder. "
        "Run build_streamlit_repo.py again."
    )
    st.stop()

qsm = get_qsm_inventory(inventory)

if qsm.empty:
    st.error("No valid reconstructed QSM trees were found in the inventory.")
    st.stop()

if "treeID" in qsm.columns:
    qsm["treeID"] = pd.to_numeric(qsm["treeID"], errors="coerce").astype("Int64")

if not manifest.empty and "treeID" in manifest.columns:
    manifest["treeID"] = pd.to_numeric(
        manifest["treeID"], errors="coerce"
    ).astype("Int64")


# ============================================================
# HEADER
# ============================================================

report_title = meta.get("title") or "Arbor Interactive Forest Explorer"

st.title(f"🌲 {report_title}")
st.caption(
    "Streamlit edition of the Arbor / QSF report. "
    "Select a tree to inspect its reconstructed QSM together with "
    "the matching TLS/MLS point cloud."
)

with st.sidebar:
    st.header("Arbor QSF Explorer")
    st.write(f"Reconstructed QSM trees: **{len(qsm):,}**")
    st.write(f"Segmented tree IDs: **{len(inventory):,}**")

    if meta.get("source_html"):
        st.caption(f"Source report: {meta['source_html']}")

    st.divider()

    available_tree_ids = sorted(
        int(x) for x in qsm["treeID"].dropna().unique()
    )

    if "selected_tree" not in st.session_state:
        st.session_state.selected_tree = available_tree_ids[0]

    current_id = int(st.session_state.selected_tree)
    if current_id not in available_tree_ids:
        current_id = available_tree_ids[0]

    select_index = available_tree_ids.index(current_id)
    chosen_id = st.selectbox(
        "Selected tree",
        available_tree_ids,
        index=select_index,
    )

    if int(chosen_id) != int(st.session_state.selected_tree):
        st.session_state.selected_tree = int(chosen_id)


# ============================================================
# TABS
# ============================================================

tab_overview, tab_tree, tab_structure, tab_reclass, tab_inventory, tab_about = st.tabs(
    [
        "Overview",
        "Tree explorer",
        "Forest structure",
        "QSF reclassification",
        "Inventory",
        "About",
    ]
)


# ============================================================
# OVERVIEW
# ============================================================

with tab_overview:
    total_volume = finite_numeric(qsm["Volume_total_m3"]).sum()
    mean_dbh = finite_numeric(qsm["DBH_cm"]).mean()
    mean_h = finite_numeric(qsm["H_m"]).mean()

    total_ba = (
        finite_numeric(qsm["BA_m2"]).sum()
        if "BA_m2" in qsm.columns
        else np.nan
    )

    stem_volume = (
        finite_numeric(qsm["Stem_volume_m3"]).sum()
        if "Stem_volume_m3" in qsm.columns
        else np.nan
    )

    branch_volume = (
        finite_numeric(qsm["Branch_volume_total_m3"]).sum()
        if "Branch_volume_total_m3" in qsm.columns
        else np.nan
    )

    area_m2 = np.nan
    density_ha = np.nan
    ba_ha = np.nan
    volume_ha = np.nan

    if {"X_tree", "Y_tree"}.issubset(qsm.columns):
        x = finite_numeric(qsm["X_tree"])
        y = finite_numeric(qsm["Y_tree"])
        valid = x.notna() & y.notna()

        if valid.sum() > 1:
            area_m2 = (x[valid].max() - x[valid].min()) * (
                y[valid].max() - y[valid].min()
            )

            if area_m2 > 0:
                density_ha = len(qsm) / area_m2 * 10000
                ba_ha = total_ba / area_m2 * 10000
                volume_ha = total_volume / area_m2 * 10000

    row1 = st.columns(4)
    row1[0].metric("QSM trees", f"{len(qsm):,}")
    row1[1].metric("Mean DBH", fmt(mean_dbh, 1, " cm"))
    row1[2].metric("Mean height", fmt(mean_h, 2, " m"))
    row1[3].metric("Total woody volume", fmt(total_volume, 2, " m³"))

    row2 = st.columns(4)
    row2[0].metric("Basal area", fmt(total_ba, 2, " m²"))
    row2[1].metric("Density", fmt(density_ha, 1, " trees/ha"))
    row2[2].metric("Volume / ha", fmt(volume_ha, 1, " m³/ha"))
    row2[3].metric("Basal area / ha", fmt(ba_ha, 1, " m²/ha"))

    if np.isfinite(stem_volume) and np.isfinite(branch_volume):
        allocation = pd.DataFrame(
            {
                "Component": ["Stem", "Branches"],
                "Volume_m3": [stem_volume, branch_volume],
            }
        )
        fig = px.pie(
            allocation,
            names="Component",
            values="Volume_m3",
            title="Stand-level woody-volume allocation",
            hole=0.35,
        )
        st.plotly_chart(fig, width="stretch")


# ============================================================
# TREE EXPLORER
# ============================================================

with tab_tree:
    st.subheader("Select a tree from the map")

    if not {"X_tree", "Y_tree", "treeID"}.issubset(qsm.columns):
        st.warning("Tree position fields are not available in the inventory.")
    else:
        map_df = qsm.copy()
        map_df["X_tree"] = finite_numeric(map_df["X_tree"])
        map_df["Y_tree"] = finite_numeric(map_df["Y_tree"])
        map_df = map_df[
            map_df["X_tree"].notna() & map_df["Y_tree"].notna()
        ].copy()

        fig_map = px.scatter(
            map_df,
            x="X_tree",
            y="Y_tree",
            color="Volume_total_m3",
            size="DBH_cm",
            custom_data=["treeID"],
            hover_data={
                "treeID": True,
                "DBH_cm": ":.1f",
                "H_m": ":.2f",
                "Volume_total_m3": ":.3f",
                "X_tree": False,
                "Y_tree": False,
            },
            color_continuous_scale="Viridis",
            title="Click a reconstructed tree",
        )

        fig_map.update_yaxes(
            scaleanchor="x",
            scaleratio=1,
        )
        fig_map.update_layout(
            height=620,
            clickmode="event+select",
        )

        event = st.plotly_chart(
            fig_map,
            key="tree_map",
            width="stretch",
            on_select="rerun",
            selection_mode="points",
            config={
                "scrollZoom": True,
                "displaylogo": False,
            },
        )

        try:
            selected_points = event.selection.points
        except Exception:
            selected_points = []

        if selected_points:
            custom = selected_points[0].get("customdata")
            if isinstance(custom, (list, tuple)) and custom:
                clicked_id = int(custom[0])
            else:
                clicked_id = int(custom)

            if clicked_id != int(st.session_state.selected_tree):
                st.session_state.selected_tree = clicked_id

    selected_id = int(st.session_state.selected_tree)
    selected = qsm[qsm["treeID"] == selected_id].copy()

    if selected.empty:
        st.warning(f"Tree {selected_id} was not found.")
    else:
        t = selected.iloc[0]

        st.markdown(f"### Tree {selected_id}")

        cols = st.columns(6)
        cols[0].metric("DBH", fmt(t.get("DBH_cm"), 1, " cm"))
        cols[1].metric("Height", fmt(t.get("H_m"), 2, " m"))
        cols[2].metric(
            "Volume", fmt(t.get("Volume_total_m3"), 3, " m³")
        )
        cols[3].metric(
            "Stem volume", fmt(t.get("Stem_volume_m3"), 3, " m³")
        )
        cols[4].metric(
            "Branch volume",
            fmt(t.get("Branch_volume_total_m3"), 3, " m³"),
        )
        cols[5].metric(
            "Branches",
            "NA"
            if pd.isna(t.get("Branch_count"))
            else f"{int(t.get('Branch_count')):,}",
        )

        viewer_path = None

        if not manifest.empty:
            m = manifest[manifest["treeID"] == selected_id]
            if not m.empty:
                viewer_value = m.iloc[0].get("viewer_file")
                viewer_path = resolve_viewer_path(viewer_value)

        if viewer_path is None:
            fallback = DATA / "QSM_viewers" / f"tree_{selected_id:05d}.html"
            if fallback.exists():
                viewer_path = fallback.resolve()

        if viewer_path is None:
            st.warning(
                "No individual QSM viewer HTML was found for this tree."
            )
        else:
            st.caption(
                "The 3D viewer overlays the reconstructed QSM cylinders "
                "with the sampled point cloud from the same segmented tree. "
                "Use the legend to hide or show wood, foliage and QSM components."
            )

            with st.spinner(f"Loading 3D QSM for tree {selected_id}..."):
                viewer_html = inline_html_file(
                    str(viewer_path),
                    viewer_path.stat().st_mtime_ns,
                )

            components.html(
                viewer_html,
                height=900,
                scrolling=True,
            )


# ============================================================
# FOREST STRUCTURE
# ============================================================

with tab_structure:
    st.subheader("Allometry")

    c1, c2 = st.columns(2)

    fig = px.scatter(
        qsm,
        x="DBH_cm",
        y="H_m",
        color="Volume_total_m3",
        size="Volume_total_m3",
        hover_data=["treeID"],
        color_continuous_scale="Viridis",
        title="Height vs DBH",
    )
    c1.plotly_chart(fig, width="stretch")

    fig = px.scatter(
        qsm,
        x="DBH_cm",
        y="Volume_total_m3",
        color="H_m",
        size="H_m",
        hover_data=["treeID"],
        color_continuous_scale="Viridis",
        title="QSM volume vs DBH",
    )
    c2.plotly_chart(fig, width="stretch")

    st.subheader("Distributions")

    d1, d2, d3 = st.columns(3)
    d1.plotly_chart(
        px.histogram(qsm, x="DBH_cm", nbins=30, title="DBH"),
        width="stretch",
    )
    d2.plotly_chart(
        px.histogram(qsm, x="H_m", nbins=30, title="Height"),
        width="stretch",
    )
    d3.plotly_chart(
        px.histogram(
            qsm,
            x="Volume_total_m3",
            nbins=30,
            title="Woody volume",
        ),
        width="stretch",
    )

    if {
        "B1_primary_volume_m3",
        "B2_secondary_volume_m3",
        "B3_tertiary_plus_volume_m3",
    }.issubset(qsm.columns):
        branch_summary = pd.DataFrame(
            {
                "Branch order": [
                    "Primary",
                    "Secondary",
                    "Tertiary+",
                ],
                "Volume_m3": [
                    finite_numeric(
                        qsm["B1_primary_volume_m3"]
                    ).sum(),
                    finite_numeric(
                        qsm["B2_secondary_volume_m3"]
                    ).sum(),
                    finite_numeric(
                        qsm["B3_tertiary_plus_volume_m3"]
                    ).sum(),
                ],
            }
        )
        st.plotly_chart(
            px.bar(
                branch_summary,
                x="Branch order",
                y="Volume_m3",
                title="Branch volume by branching order",
            ),
            width="stretch",
        )

    if not ranking.empty:
        st.subheader("Structurally prominent trees")

        cols = [
            c
            for c in [
                "Rank_structural",
                "treeID",
                "Structural_score",
                "DBH_cm",
                "H_m",
                "Volume_total_m3",
                "Branch_count",
                "Max_branch_order",
            ]
            if c in ranking.columns
        ]

        st.dataframe(
            ranking[cols].head(30),
            width="stretch",
            hide_index=True,
        )


# ============================================================
# QSF RECLASSIFICATION
# ============================================================

with tab_reclass:
    st.subheader("QSF-assisted semantic reclassification")

    st.write(
        "This section keeps the quantitative before/after summary. "
        "The heavy forest-wide 3D comparison is intentionally omitted "
        "because the point cloud is now inspected directly against each "
        "selected QSM in the Tree explorer."
    )

    def semantic_counts(df: pd.DataFrame, stage: str) -> pd.DataFrame:
        if df.empty or "semantic_label" not in df.columns:
            return pd.DataFrame()
        out = (
            df["semantic_label"]
            .astype(str)
            .value_counts()
            .rename_axis("semantic_label")
            .reset_index(name="N")
        )
        out["Stage"] = stage
        return out

    counts = pd.concat(
        [
            semantic_counts(semantic_before, "Before"),
            semantic_counts(semantic_after, "After"),
        ],
        ignore_index=True,
    )

    if not counts.empty:
        fig = px.bar(
            counts,
            x="semantic_label",
            y="N",
            color="Stage",
            barmode="group",
            title="Sampled point counts by semantic class",
        )
        st.plotly_chart(fig, width="stretch")

    if (
        not semantic_transition.empty
        and {
            "semantic_before",
            "semantic_after",
            "N",
        }.issubset(semantic_transition.columns)
    ):
        trans = semantic_transition.copy()
        trans["N"] = finite_numeric(trans["N"]).fillna(0)

        before_names = [
            f"Before: {x}"
            for x in trans["semantic_before"].astype(str)
        ]
        after_names = [
            f"After: {x}"
            for x in trans["semantic_after"].astype(str)
        ]
        labels = list(dict.fromkeys(before_names + after_names))
        label_index = {name: i for i, name in enumerate(labels)}

        source = [
            label_index[f"Before: {x}"]
            for x in trans["semantic_before"].astype(str)
        ]
        target = [
            label_index[f"After: {x}"]
            for x in trans["semantic_after"].astype(str)
        ]

        fig = go.Figure(
            go.Sankey(
                node=dict(label=labels, pad=15, thickness=18),
                link=dict(
                    source=source,
                    target=target,
                    value=trans["N"].tolist(),
                ),
            )
        )
        fig.update_layout(
            title="Point-class transitions produced by QSF reclassification",
            height=600,
        )
        st.plotly_chart(fig, width="stretch")
    else:
        st.info("Semantic transition table is not available.")


# ============================================================
# COMPLETE INVENTORY
# ============================================================

with tab_inventory:
    st.subheader("Complete tree inventory")

    status_col = "QSM_status" if "QSM_status" in inventory.columns else None

    if status_col:
        statuses = sorted(inventory[status_col].dropna().astype(str).unique())
        selected_status = st.multiselect(
            "QSM status",
            statuses,
            default=statuses,
        )
        display_inventory = inventory[
            inventory[status_col].astype(str).isin(selected_status)
        ].copy()
    else:
        display_inventory = inventory.copy()

    st.dataframe(
        display_inventory,
        width="stretch",
        height=650,
        hide_index=True,
    )

    st.download_button(
        "Download current inventory CSV",
        data=display_inventory.to_csv(index=False).encode("utf-8"),
        file_name="Arbor_tree_inventory.csv",
        mime="text/csv",
    )


# ============================================================
# ABOUT
# ============================================================

with tab_about:
    st.subheader("About this app")

    st.markdown(
        """
A **Quantitative Structure Model (QSM)** is a three-dimensional
representation of an individual tree that explicitly describes its
geometry and topology, including stems, branches, radii and volumes.

A **Quantitative Structure Forest (QSF)** extends this concept from
individual trees to a coherent collection of QSMs describing a forest
scene.

This Streamlit application is generated from the outputs of the Arbor
TLS/MLS workflow. The individual-tree pages retain the QSM geometry and
the sampled point-cloud overlay produced by the R processing pipeline.
"""
    )

    if meta:
        st.markdown("#### Source HTML metadata")
        st.json(meta)

    st.markdown(
        """
#### Sharing model

The application reads files bundled with the GitHub repository. No LAS
or LAZ file is required by the deployed app. The heavy point-cloud
processing remains in the R workflow; Streamlit only serves the
pre-generated report data and individual-tree viewers.
"""
    )
